# Generated by Django 5.1.1 on 2024-10-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TennisClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('established_date', models.DateField()),
                ('membership_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
                ('tennis_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis_app.tennisclub')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('participants', models.ManyToManyField(to='tennis_app.member')),
                ('tennis_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis_app.tennisclub')),
            ],
        ),
    ]
